### ISSUE TITLE
Config file doesn't work?

### ISSUE THREAD

**Issue by lnicola** [alvistar/immich-albums#10]
I have this `config.yaml`:

```yaml
---
 api-key: 'hello'
 api-host: 'http://127.0.0.1:2283/api'
 original-path: '/tank/path'
 replace-path: '/usr/src/app/external'
```

(also tried without `---` and quotes)

But I get:

```sh
$ im -r --dry-run --config config.yaml /tank/path
Loading config from: config.yaml
Usage: im [OPTIONS] PATH
Try 'im --help' for help.

Error: Missing option '--api-key'.
```

Probably missing something though.

**Comment by ChrislyBear-GH** [comment]
Same.

**Comment by alvistar** [comment]
Issue is that variables in yaml should use underscore instead of hypen.

Ex.
api_key instead of api-key

It was already working but documentation was wrrong. I updated it.
