### ISSUE TITLE
im --help error

### ISSUE THREAD

**Issue by Kirill-KKK** [alvistar/immich-albums#13]
What I have:

Description:    Ubuntu 22.04.4 LTS
Poetry (version 1.2.0)
Python 3.10.12

I followed the installation instructions, but when entering the command:
im --help
I get im: command not found.
I can't update Poetry to a newer version, maybe that's the case? What is this im command? Thank you in advance

**Comment by mmxhello** [comment]
Faced the same issue, solved just by running `poetry shell` with `sudo`
