### ISSUE TITLE
useable to import an create immich album "internal" ?

### ISSUE THREAD

**Issue by daschillinger** [alvistar/immich-albums#6]
can I use this script to upload the files and create internal albums?
Otherwise I will have to review all photos for junk as external albums are read only, right?

2nd question if I may: what happens to photos which are in multiple albums or in the root folder(duplicates)?

**Comment by alvistar** [comment]
1) You do not upload files with this script.  You import them as external libraries inside immich
2) A photo can be in many albums as you wish. This script anyway will reflect your folder structure
